jobs:
  build:
    continue-on-error: ${{ matrix.experimental }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        persist-credentials: false
    - continue-on-error: true
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        server-id: apache.snapshots.https
        server-password: NEXUS_PW
        server-username: NEXUS_USER
    - continue-on-error: true
      name: Build with Maven
      run: mvn --show-version --batch-mode --no-transfer-progress -DtrimStackTrace=false
    - continue-on-error: true
      env:
        NEXUS_PW: ${{ secrets.NEXUS_PW }}
        NEXUS_USER: ${{ secrets.NEXUS_USER }}
      if: matrix.deploy && github.repository == 'apache/commons-io' && github.ref_name
        == 'master'
      name: Deploy SNAPSHOT using minimal build
      run: 'echo "Deploy SNAPSHOT" >> $GITHUB_STEP_SUMMARY; mvn --show-version --batch-mode
        --no-transfer-progress deploy -Dgpg.skip  -DskipTests -Drat.skip -Djacoco.skip
        -Dcyclonedx.skip -Dspotbugs.skip -Dspdx.skip -Dpmd.skip

        '
    strategy:
      fail-fast: false
      matrix:
        experimental:
        - false
        include:
        - deploy: true
          experimental: false
          java: 8
          os: ubuntu-latest
        java:
        - 8
        - 11
        - 17
        - 21
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
permissions:
  contents: read
